//! Config mutation orchestration: apply a [`Mutation`] to the on-disk desired
//! state via read → surgical edit → validate → atomic write. This is the shared
//! core that both the CLI (when the daemon is stopped) and the daemon (when it
//! is running) call, so the write is identical either way — only *who* runs it
//! differs (config-mutation-model, ADR 0009). Validation is enforced on both
//! paths; on any error the file is left untouched (last-known-good preserved).
//!
//! Consumed by the dual-mode dispatch and the `jobs` mutation commands
//! (PDC-81–85); until those wire up, exercised only by its tests.
#![allow(dead_code)]

use std::path::Path;

use crate::{config, config_edit, validation};

/// The user-facing result of a dispatched mutation. `Refused` carries a message
/// for an expected failure (unknown job, invalid result) — distinct from a
/// transport error, which propagates as `Err` from the dispatcher.
pub(crate) enum Outcome {
    Applied,
    Refused(String),
}

/// A requested change to the desired-state YAML.
#[derive(Debug, PartialEq, Eq)]
pub(crate) enum Mutation {
    /// Pause a job: set `enabled: false`.
    Pause(String),
    /// Resume a job: set `enabled: true`.
    Resume(String),
    /// Remove a job's block entirely.
    Remove(String),
    /// Append a pre-formatted job block (generated by `jobs add`).
    Add(String),
    /// Replace the whole file with hand-edited content (from `jobs edit`).
    Replace(String),
}

/// Apply `mutation` to the config at `path`: read, surgically edit, validate,
/// and atomically persist. On any error (unknown job, invalid result) the file
/// is left untouched.
pub(crate) fn apply_to_disk(path: &Path, mutation: &Mutation) -> anyhow::Result<()> {
    let candidate = render(path, mutation)?;
    validate(&candidate)?;
    config_edit::atomic_write(path, &candidate)
}

/// The frozen IPC method + params for a mutation (CLI → daemon, daemon running).
/// Per-operation methods map 1:1 to the surgical primitives; `config.replace`
/// carries the whole hand-edited file for `jobs edit`.
pub(crate) fn mutation_to_request(m: &Mutation) -> (&'static str, serde_json::Value) {
    use serde_json::json;
    match m {
        Mutation::Pause(id) => ("jobs.pause", json!({ "id": id })),
        Mutation::Resume(id) => ("jobs.resume", json!({ "id": id })),
        Mutation::Remove(id) => ("jobs.remove", json!({ "id": id })),
        Mutation::Add(block) => ("jobs.add", json!({ "block": block })),
        Mutation::Replace(content) => ("config.replace", json!({ "content": content })),
    }
}

/// Inverse of [`mutation_to_request`] (daemon receive side).
pub(crate) fn request_to_mutation(
    method: &str,
    params: &serde_json::Value,
) -> anyhow::Result<Mutation> {
    let s = |k: &str| -> anyhow::Result<String> {
        params
            .get(k)
            .and_then(serde_json::Value::as_str)
            .map(str::to_owned)
            .ok_or_else(|| anyhow::anyhow!("missing string param `{k}`"))
    };
    Ok(match method {
        "jobs.pause" => Mutation::Pause(s("id")?),
        "jobs.resume" => Mutation::Resume(s("id")?),
        "jobs.remove" => Mutation::Remove(s("id")?),
        "jobs.add" => Mutation::Add(s("block")?),
        "config.replace" => Mutation::Replace(s("content")?),
        other => anyhow::bail!("unknown mutation method: {other}"),
    })
}

/// Whether `method` is a config-mutating IPC method owned by this module.
pub(crate) fn is_mutation_method(method: &str) -> bool {
    matches!(
        method,
        "jobs.pause" | "jobs.resume" | "jobs.remove" | "jobs.add" | "config.replace"
    )
}

/// Daemon-side handling of a mutation IPC request: decode → apply to disk. On
/// success the caller signals a reload; on failure it returns the `(code, msg)`
/// to the IPC client. The file is only ever touched on success ([`apply_to_disk`]).
pub(crate) fn handle_ipc(
    method: &str,
    params: &serde_json::Value,
    config_path: &Path,
) -> Result<(), (String, String)> {
    let mutation = request_to_mutation(method, params)
        .map_err(|e| ("bad_params".to_owned(), e.to_string()))?;
    apply_to_disk(config_path, &mutation).map_err(|e| ("mutation_failed".to_owned(), e.to_string()))
}

/// Produce the candidate YAML for `mutation` without persisting it. Surgical
/// mutations read and edit the current file; `Replace` carries its own content.
fn render(path: &Path, mutation: &Mutation) -> anyhow::Result<String> {
    let read_current = || -> anyhow::Result<String> {
        std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("cannot read {}: {e}", path.display()))
    };
    match mutation {
        Mutation::Pause(id) => config_edit::set_enabled(&read_current()?, id, false),
        Mutation::Resume(id) => config_edit::set_enabled(&read_current()?, id, true),
        Mutation::Remove(id) => config_edit::remove_job(&read_current()?, id),
        Mutation::Add(block) => config_edit::append_job(&read_current()?, block),
        Mutation::Replace(content) => Ok(content.clone()),
    }
}

/// Reject a candidate config that fails to parse or carries any error diagnostic,
/// so a mutation never persists an invalid desired state.
fn validate(yaml: &str) -> anyhow::Result<()> {
    let raw = config::parse(yaml)
        .map_err(|d| anyhow::anyhow!("resulting config is invalid: {} ({})", d.message, d.path))?;
    if validation::validate_config(&raw)
        .iter()
        .any(|d| d.is_error())
    {
        anyhow::bail!("resulting config is invalid; run `periodic validate` for details");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const CONFIG: &str = "\
version: 1
jobs:
  - id: cleanup            # nightly sweep
    enabled: true
    schedule:
      every: 15m
    execution:
      command: /usr/bin/true
";

    fn temp_config(content: &str) -> (tempfile::TempDir, std::path::PathBuf) {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("periodic.config.yaml");
        std::fs::write(&path, content).unwrap();
        (dir, path)
    }

    #[test]
    fn pause_writes_disabled_and_preserves_comments() {
        let (_dir, path) = temp_config(CONFIG);
        apply_to_disk(&path, &Mutation::Pause("cleanup".to_owned())).expect("pause should succeed");

        let out = std::fs::read_to_string(&path).unwrap();
        assert!(
            out.contains("enabled: false"),
            "should be paused on disk:\n{out}"
        );
        assert!(
            out.contains("# nightly sweep"),
            "comment preserved on disk:\n{out}"
        );
    }

    #[test]
    fn replace_persists_hand_edited_content() {
        let (_dir, path) = temp_config(CONFIG);
        let edited = CONFIG.replace("/usr/bin/true", "/usr/bin/tidy");
        apply_to_disk(&path, &Mutation::Replace(edited.clone())).expect("replace should succeed");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), edited);
    }

    #[test]
    fn remove_persists_excision() {
        let (_dir, path) = temp_config(CONFIG);
        apply_to_disk(&path, &Mutation::Remove("cleanup".to_owned()))
            .expect("remove should succeed");
        assert!(
            !std::fs::read_to_string(&path)
                .unwrap()
                .contains("id: cleanup")
        );
    }

    #[test]
    fn structurally_invalid_replace_leaves_file_untouched() {
        let (_dir, path) = temp_config(CONFIG);
        let err = apply_to_disk(&path, &Mutation::Replace("not: [valid".to_owned())).unwrap_err();
        assert!(
            err.to_string().contains("invalid"),
            "should report invalid: {err}"
        );
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            CONFIG,
            "last-known-good must be preserved on a rejected mutation"
        );
    }

    #[test]
    fn validation_error_blocks_persist() {
        let (_dir, path) = temp_config(CONFIG);
        // `every: 45m` violates the divisor rule (decision 0001) -> validation error.
        let block =
            "  - id: bad\n    schedule:\n      every: 45m\n    execution:\n      command: /bin/x";
        let err = apply_to_disk(&path, &Mutation::Add(block.to_owned())).unwrap_err();
        assert!(
            err.to_string().contains("invalid"),
            "should reject invalid schedule: {err}"
        );
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            CONFIG,
            "an invalid appended job must not be persisted"
        );
    }

    #[test]
    fn mutating_unknown_job_errors_without_writing() {
        let (_dir, path) = temp_config(CONFIG);
        assert!(apply_to_disk(&path, &Mutation::Remove("ghost".to_owned())).is_err());
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            CONFIG,
            "file untouched"
        );
    }

    #[test]
    fn mutation_request_round_trips_through_the_wire_mapping() {
        for m in [
            Mutation::Pause("a".into()),
            Mutation::Resume("b".into()),
            Mutation::Remove("c".into()),
            Mutation::Add("  - id: d".into()),
            Mutation::Replace("version: 1\n".into()),
        ] {
            let (method, params) = mutation_to_request(&m);
            assert!(
                is_mutation_method(method),
                "{method} should be a mutation method"
            );
            assert_eq!(request_to_mutation(method, &params).unwrap(), m);
        }
        assert!(request_to_mutation("daemon.status", &serde_json::json!({})).is_err());
        assert!(!is_mutation_method("daemon.reload"));
    }

    #[test]
    fn handle_ipc_applies_and_maps_errors() {
        let (_dir, path) = temp_config(CONFIG);
        // Happy path: pauses on disk.
        handle_ipc("jobs.pause", &serde_json::json!({ "id": "cleanup" }), &path).unwrap();
        assert!(
            std::fs::read_to_string(&path)
                .unwrap()
                .contains("enabled: false")
        );

        // Bad params -> bad_params code, file untouched.
        let (code, _) = handle_ipc("jobs.remove", &serde_json::json!({}), &path).unwrap_err();
        assert_eq!(code, "bad_params");

        // Apply failure (unknown job) -> mutation_failed code.
        let (code, _) =
            handle_ipc("jobs.remove", &serde_json::json!({ "id": "ghost" }), &path).unwrap_err();
        assert_eq!(code, "mutation_failed");
    }
}
